version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t awsdotnet .
      - docker tag awsdotnet:latest 663265013238.dkr.ecr.ap-south-1.amazonaws.com/awsdotnet:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 663265013238.dkr.ecr.ap-south-1.amazonaws.com/awsdotnet:$IMAGE_TAG

